export const stablecryptoTokenSearchCandidate = {
  provider_id: "merit-systems-stablecrypto-market-data",
  provider_name: "StableCrypto",
  category: "finance/data",
  benchmark_intent: "token search",
  mapping_status: "verified",
  execution_evidence_status: "proven",
  verified_at: "2026-05-17",
  proven_at: "2026-05-17",
  proof_source: "infopunks-pay-sh-agent-harness",
  proof_reference: "live-proofs/stablecrypto-token-search-paid-execution-2026-05-17.md",
  endpoint_url: "https://stablecrypto.dev/api/coingecko/onchain/search",
  method: "POST",
  request_shape_example: { query: "SOL" },
  notes: "Paid execution succeeded for StableCrypto token-search route. This proves route execution, not benchmark readiness or superiority.",
} as const;
